print("My name is Inara.")
print("I was born in Seattle.")
print("My favorite drink is Sprite.")
print("Now I want to learn about you.")
their_name = input("What's your name?")
print(f"Hi {their_name}, nice to meet you.")